### PR TITLE
Tasks Section

### PR DESCRIPTION
**Pull request by bortami**
**What you should see**
As a user, you should be able to login. Please use Steve/password for testing. Steve has friends, events, and tasks to complete.
After login, the friends, tasks, and events sections should all load with the current user's information.
In the tasks section, Steve will already have a list of tasks he needs to do.
beside each task is a check box.
Clicking on the checkbox will cause the task to be removed from the DOM  and that task is marked as complete in the database.
Clicking on a task name will pop up an edit form.
pressing Enter or the Save Button will update that task, and an updated task list should appear. 
Pressing the cancel button at any time will send the user back to the uncomplete task list with add new task button at the bottom.
the Add New Task button will populate a form, once filled out and save is clicked. The task list will refresh with the newest task at the bottom.

**# To Test this, you must have a JSON database running on port 8088.**

 I've include a db readMe file on how to add a JSON server, and a db boilerplate txt file. The contents of the txt file should be copied to api/db.json for proper functonality.

### CODE REVIEW

**Comment by bortami** [comment]
fixed the issue where the save new task was reprinting and posting multiple times.
it should now only reprint the list once and post once

**Comment by Cluttered04** [comment]
🎏 🐟

**Comment by bortami** [comment]
tasks now clears on logout

**Comment by sydneywait** [comment]
👍

**Pull request merged**
